DROP TABLE T_TENANTS;

CREATE TABLE T_TENANTS (
  ID VARCHAR ,
  NAME VARCHAR ,
  STATE VARCHAR
);

DROP TABLE T_TENANT_OPERATIONS;

CREATE TABLE T_TENANT_OPERATIONS (
  ID VARCHAR ,
  TENANT_ID VARCHAR,
  ACTION VARCHAR,
  ACTION_TIME DATE,
  IS_SUCCESSFUL VARCHAR
);

DROP TABLE T_AUDIT_LOGS;

CREATE TABLE T_AUDIT_LOGS(
  ID VARCHAR ,
  WHO VARCHAR ,
  ACTION VARCHAR ,
  ACTION_TIME NUMBER ,
  TARGET VARCHAR,
  TARGET_TYPE VARCHAR ,
  TARGET_ID VARCHAR
);